config/routes.rb
Rails.application.routes.draw do
  root :to => 'photos#home'

  get 'search' => 'photos#search'

  get 'largeimage' => 'photos#largeimage'

end

app/models/photo.rb
class Photo
  include ActiveModel::Model

#attributes for photo search
  attr_accessor :id, :title, :description, :link_url, :thumbnail_url, :original_url


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
 include PhotosHelper

  def home

  end

#format for ajax
  def largeimage

    choice = {
      :largeimageurl =>  params[:limageurl],
      :largeimageid =>   params[:limageid],
      :largeimagetitle =>   params[:limagetitle]
    }

    respond_to do |format|
      format.html {}
      format.js {render :json => choice }
      format.json {render :json => choice }
    end

  end

# Search photos and arrange paginate
  def search

    if params[:search].blank?
      flash.now[:notice]= "Please start to search."
    else
      search = params[:search]
      get_flickr_images(search)
      @images = @flickr_images.paginate(page: params[:page], per_page: 50)
      flash.now[:annouce] = "Click a thumbnail image to view the larger size image."
    end
    render :home

  end

end

app/controllers/test_flickr.rb
# require 'flickraw'

# begin
#         extras = 'owner_name, views, date_taken, geo'

#         if params[:category] == 'user'
#           user = flickr.people.findByUsername(:username => params[:search_term])
#           search_term = user.nsid
#           type = 'user_id'
#           params[:sort] = 'date-posted-desc' if params[:sort].nil?
#         else
#           search_term = params[:search_term]
#           type = 'text'
#           params[:sort] = 'relevance' if params[:sort].nil?
#         end

#         @photos = flickr.photos.search(:sort => params[:sort], type.to_sym => search_term, :extras => extras)
#       rescue Exception => e
#         flash[:error] = 'No results'
#         logger.info "#{e.message}"
# end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Flickr Photo Search"

    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end

  end
end

app/helpers/photos_helper.rb
#Search function of flickr photo
module PhotosHelper
  require 'flickraw'

  # flickr api keys
    FlickRaw.api_key       = ENV["API_KEY"]
    FlickRaw.shared_secret = ENV["SHARED_SECRET"]
    flickr.access_token =   ENV["ACCESS_TOKEN"]
    flickr.access_secret = ENV["ACCESS_SECRET"]

  def get_flickr_images(text)
    thumbnail_size = "s" #small square 75x75
    medium_size = "n" # 300 on longest side

    flickr = FlickRaw::Flickr.new

    photos = flickr.photos.search(text: text, sort: "relevant", per_page: 500)


    @flickr_images = []
    photos.each do |photo|
      @flickr_images << Photo.new(
        id: photo["id"],
        title: photo["title"],
        description: "",
        link_url: "http://www.flickr.com/photos/#{photo["owner"]}/#{photo["id"]}",
        thumbnail_url: "http://farm#{photo["farm"]}.staticflickr.com/#{photo["server"]}/#{photo["id"]}_#{photo["secret"]}_#{thumbnail_size}.jpg",
        original_url: "http://farm#{photo["farm"]}.staticflickr.com/#{photo["server"]}/#{photo["id"]}_#{photo["secret"]}_#{medium_size}.jpg"
      )
    end
    @flickr_images

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <%= yield %>
  </div>
</body>
</html>

app/views/photos/_form.html.erb
<!-- Search photo-->
  <%= form_tag search_path, method: "get", :class=>"tag_size" do %>

    <div class="search">
      <%= text_field_tag :search, nil, :autofocus => true, :placeholder => 'Type keyword to search'%>
    </div>

    <div class="submit">
    <%= submit_tag "Search", :name => nil%></div>

  <% end %>

app/views/photos/home.html.erb
<% provide(:title, 'Home') %>

<div id="header">
  <i class="fa fa-camera-retro fa-5x"></i>
    <h1>Flickr Photo Search!</h1>

  <div class="form">
    <%= render :partial => 'form' %>
  </div>
  <div class="announce">
    <%= flash[:annouce] %>
  </div>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
</div><!-- div header end -->

<div id="image_main">
  <div class="search_result">
    <!-- Pagination -->
    <div id="page_style">
      <% if @images %>
        <%= will_paginate @images %>
      <% end %>
    </div>
    <!-- click a thumbnail image and open the larger image -->
    <div class="image_block">
      <% @images.each do |image| %>
       <div class="single_image">
            <%= link_to (image_tag(image.thumbnail_url, :size => '75x75')), largeimage_path, data: {remote: :true, type: :json, params: {limageurl: image.original_url, limageid: image.id, limagetitle: image.title}.to_param} %>
       </div>
      <%end if @images%>
    </div>
  </div>
  <!-- Insert large image with title, id here -->
  <div class="large"></div>
</div>